joseikun_keyless/joseikun/joseikun/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jsk.urls')),
]

# 画像ファイル表示のためのURL（？）
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

joseikun_keyless/joseikun/jsk/urls.py
from django.urls import path
from . import views

app_name = 'jsk'

urlpatterns = [
    path('', views.Top.as_view(), name='top'),
    # ログイン/ログアウト
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    # アカウント仮登録～本登録完了
    path('user_create_input/', views.UserDataInput.as_view(), name='user_create_input'),
    path('user_create_confirm/', views.UserDataConfirm.as_view(), name='user_create_confirm'),
    path('user_create/done', views.UserCreateDone.as_view(), name='user_create_done'),
    path('user_create/complete/<token>/', views.UserCreateComplete.as_view(), name='user_create_complete'),
    # アカウントの詳細表示・更新・削除
    path('user_detail/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('user_update/<int:pk>/', views.UserUpdate.as_view(), name='user_update'),
    # ここに編集確認画面を入れる
    path('user_delete/<int:pk>/', views.UserDelete.as_view(), name='user_delete'),
    # パスワードの再設定
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    # パスワードの再発行
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    # path('password_reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirm(), name='password_reset_confirm'),
    path('password_reset/complete/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
    # ファイルのアップロード
    path('file_upload_text/', views.FileUploadText.as_view(), name='file_upload_text'),
    path('file_upload_image/', views.FileUploadImage.as_view(), name='file_upload_image'),
    # 完了画面は render() で対応しました。
    path('file_upload_done/<int:user_pk>/<int:pk>/<str:token>', views.FileUploadDone.as_view(), name='file_upload_done'),
    path('file_update_done/<int:user_pk>/<int:pk>/<str:token>', views.FileUpdateDone.as_view(), name='file_update_done'),
    # ファイルの一覧表示
    # path('file_search/<int:pk>/', views.FileSearch.as_view(), name='file_search'),
    path('file_search/', views.FileSearch.as_view(), name='file_search'),
    path('file_download/',views.FileDownload,name='file_download'),
    path('file_download_pic/',views.FileDownloadPic,name='file_download_pic'),
    path('file_detail/<int:user_pk>/<int:pk>/', views.FileDetail.as_view(), name='file_detail'),
    # ファイルの編集
    path('file_update_text/<int:user_pk>/<int:pk>', views.FileTextUpdate.as_view(), name='file_update_text'),
    # タグの編集
    path('file_update_tags/<int:user_pk>/<int:pk>/', views.FileTagUpdate.as_view(), name='file_update_tags'),
    path('text_to_tags/<int:user_pk>/<int:pk>/', views.TextToTags.as_view(), name='text_to_tags'),
    # ファイルの削除
    path('file_delete/', views.FileDelete.as_view(), name='file_delete'),
    # なにかいかがわしいことをした場合
    path('invalid_action_error/', views.ErrorView.as_view(), name='error_view'),
    #開発用ページ
    #path('develop/fileupload/',views.DevelopFileUpload,name='develop_fileupload'),
    #path('develop/fileupload_result/',views.DevelopFileUploadResult,name='develop_fileupload_result'),
    #path('develop/fileselect/',views.DevelopFileSelect,name='develop_fileselect'),
    #path('develop/fileselect_result/',views.DevelopFileSelectResult,name='develop_fileselect_result'),
    #path('develop/fileselect_result2/',views.DevelopFileSelectResult2,name='develop_fileselect_result2'),
    #path('develop/filedownload/',views.DevelopFileDownload,name='develop_filedownload'),
    #path('develop/filedownload_result/',views.DevelopFileDownloadResult,name='develop_filedownload_result'),
    #path('develop/develop_scheme/',views.DevelopScheme,name='develop_scheme'),
    #path('develop/develop_schemedownload/',views.DevelopSchemeDownload,name='develop_schemedownload'),
]

joseikun_keyless/joseikun/jsk/views.py
from lib2to3.pgen2 import token
import smtplib, docx, re, datetime, uuid
import urllib.parse
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView,
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
)
from django.contrib.sites.shortcuts import get_current_site
from django.core.files import File
from django.core.signing import BadSignature, SignatureExpired, loads, dumps
from django.http import HttpResponseBadRequest, FileResponse ,Http404 , HttpResponseRedirect, HttpResponse
from django.shortcuts import redirect, resolve_url, render
from django.template.loader import render_to_string
from django.shortcuts import render
from django.utils import timezone
from django.urls import reverse_lazy
from django.views import generic
from jmespath import search
from matplotlib.pyplot import close
from .forms import (
    LoginForm, UserCreateForm, UserUpdateForm, MyPasswordChangeForm,
    MyPasswordResetForm, MySetPasswordForm, FileUploadTextForm,
    FileDataUpdateForm, FileTagUpdateForm, FileUploadImageForm,
    UserDeleteForm, TextToTagsForm, FileSearchForm
)
from .models import User , Filemanage
from django.db.models import Q
from email.mime.text import MIMEText
import json
from PIL import Image
from secrets import token_urlsafe

# Google-Cloud関係で必要な物
import io
import os
from google.cloud import vision
from google.oauth2 import service_account
import boto3

#Google-Cloudのクライアント作成
credential_path = './gcp_key/norse-ego-279800-dbca388726fe.json'
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = credential_path
# Instantiates a client
client = vision.ImageAnnotatorClient()

User = get_user_model()
# from django.contrib.auth.models import User これはあまりうまくない

#環境変数
FILE_PATH = ".\\download\\"
LANGUAGE_DICT = {
    'ja': '日本語',
    'en': '英語',
    'es': 'スペイン語',
    'it': 'イタリア語',
    'fr': 'フランス語',
    'pt': 'ポルトガル語',
    'de': 'ドイツ語'}

# Access key ID
ACCESS_KEY_ID = ''
# Secret access key
SECRET_ACCESS_KEY = ''
# Region name
REGION_NAME = 'ap-northeast-1'
S3_FILE_UPLOAD = ''
S3_FILE_DOWNLOAD = ''
S3_FILE_TAGS = ''
S3_FILE_PIC = ''

# メール送信
#メール送信関数
def mail_send(to_email,subject,message):
  # SMTP認証情報
#   account = "jyouseikun@gmail.com"
#   password = "bexgkklkixezgdcr"
  account = ""
  password = ""

  from_email = "情整君。  メール送信システム<" + account + ">"
  
  # MIMEの作成
  msg = MIMEText(message, "html")
  msg["Subject"] = subject
  msg["To"] = to_email
  msg["From"] = from_email
  
  # メール送信処理
  server = smtplib.SMTP("smtp.gmail.com", 587)
  server.starttls()
  server.login(account, password)
  server.send_message(msg)
  server.quit()


class Top(generic.TemplateView):
    template_name = 'jsk/top.html'
    extra_context = {
        'search_form': FileSearchForm(),
        'title': '情整君。へようこそ', 'template_name': template_name}

    def get(self, request, *args, **kwargs):
        user = self.request.user
        if user.id:
            # ログインボタンを押下した後、top画面へ遷移するところを
            # ファイル検索画面へ遷移させました
            return redirect('jsk:file_search')
        return super().get(request, *args, **kwargs)

class Login(LoginView):
    """ログイン画面"""
    form_class = LoginForm
    template_name = 'jsk/login.html'
    extra_context = {
        'search_form': FileSearchForm(),
        'title': 'ログイン', 'template_name': template_name}

    def get(self, request, *args, **kwargs):
        user = self.request.user
        if user.id:
            # ログインボタンを押下した後、top画面へ遷移するところを
            # ファイル検索画面へ遷移させました
            return redirect('jsk:file_search')
        return super().get(request, *args, **kwargs)



class Logout(LogoutView):
    """ログアウト画面"""
    template_name = 'jsk/top.html'
    extra_context = {
        'search_form': FileSearchForm(),
        'title': '情整君。へようこそ', 'template_name': template_name}

class UserDataInput(generic.FormView):
    """ユーザー情報の入力

    このビューが呼ばれるのは、以下の2箇所です。
    ・初回の入力欄表示(aタグでの遷移)
    ・確認画面から戻るを押した場合(これはPOSTで飛んできます)

    初回の入力欄表示の際は、空のフォームをuser_create_input.htmlに渡し、
    戻る場合は、POSTで飛んできたフォームデータをそのままuser_create_input.htmlに渡します。

    """
    template_name = 'jsk/user_create_input.html'
    extra_context = {
        'search_form': FileSearchForm(),
        'title': 'アカウント登録', 'template_name': template_name}
    form_class = UserCreateForm

    def get(self, request, *args, **kwargs):
        user = self.request.user
        if user.id:
            # ログインボタンを押下した後、top画面へ遷移するところを
            # ファイル検索画面へ遷移させました
            return redirect('jsk:file_search')
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        return render(self.request, 'jsk/user_create_input.html', {'form': form})

class UserDataConfirm(generic.FormView):
    """ユーザー情報の確認

    ユーザー情報入力後、「送信」を押すとこのビューが呼ばれます。(user_create_input.htmlのform action属性がこのビュー)
    データが問題なければuser_create_confirm.html(確認画面)を、入力内容に不備があればuser_create_input.html(入力画面)に
    フォームデータを渡します。

    """
    form_class = UserCreateForm
    # extra_context = {
        # 'search_form': FileSearchForm(),
    # 'title': 'ユーザー情報の確認', 'template_name': template_name}

    def get(self, request, *args, **kwargs):
        user = self.request.user
        if user.id:
            # ログインボタンを押下した後、top画面へ遷移するところを
            # ファイル検索画面へ遷移させました
            return redirect('jsk:file_search')
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        context = {
            'title': 'アカウント入力画面',
            'form': form,
            'pass1': '●●●●●●●●',
            'pass2': '●●●●●●●●',
        }
        return render(self.request, 'jsk/user_create_confirm.html', context)

    def form_invalid(self, form):
        return render(self.request, 'jsk/user_create_input.html', {'form': form})

class UserCreateDone(generic.CreateView):
    """ユーザー仮登録"""
    template_name = 'jsk/user_create_done.html'
    extra_context = {
        'search_form': FileSearchForm(),
        'title': 'アカウント仮登録', 'template_name': template_name}
    form_class = UserCreateForm

    def get(self, request, *args, **kwargs):
        user = self.request.user
        if user.id:
            # ログインボタンを押下した後、top画面へ遷移するところを
            # ファイル検索画面へ遷移させました
            return redirect('jsk:file_search')
        return super().get(request, *args, **kwargs)

    def form_invalid(self, form):
        return render(self.request, 'jsk/user_confirm_error.html', {'name': '南部隼希'})

    def form_valid(self, form):
        """仮登録と本登録用メールの発行."""
        # 仮登録と本登録の切り替えは、is_active属性を使うと簡単です。
        # 退会処理も、is_activeをFalseにするだけにしておくと捗ります。
        user = form.save(commit=False)
        user.is_active = True
        user.save()

        # アクティベーションURLの送付
        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': self.request.scheme,
            'domain': domain,
            'token': dumps(user.pk),
            'user': user,
        }
        # メール送信
        to_mail = self.request.POST['email']
        subject = render_to_string('jsk/mail_template/create/subject.txt', context)
        message = render_to_string('jsk/mail_template/create/message.txt', context)

        # user.email_user(subject, message)
        # メール送信
        mail_send(to_mail, subject, message)
        return redirect('jsk:user_create_done')

class UserCreateComplete(generic.TemplateView):
    """メール内URLアクセス後のユーザー本登録"""
    template_name = 'jsk/user_create_complete.html'
    extra_context = {
        'search_form': FileSearchForm(),
        'title': 'アカウント本登録', 'template_name': template_name}
    timeout_seconds = getattr(settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60*24*365)  # デフォルトでは1年以内

    def get(self, request, **kwargs):
        """tokenが正しければ本登録."""
        token = kwargs.get('token')
        try:
            user_pk = loads(token, max_age=self.timeout_seconds)

        # 期限切れ
        except SignatureExpired:
            return HttpResponseBadRequest()

        # tokenが間違っている
        except BadSignature:
            return HttpResponseBadRequest()

        # tokenは問題なし
        else:
            try:
                user = User.objects.get(pk=user_pk)
            except User.DoesNotExist:
                return HttpResponseBadRequest()
            else:
                # if not user.is_active:
                #     # 問題なければ本登録とする
                #     user.is_active = True
                if user.is_regist == False:
                    # 問題なければ本登録とする
                    user.is_regist = True
                    user.save()
                    return super().get(request, **kwargs)

        return HttpResponseBadRequest()

class OnlyYouMixin(UserPassesTestMixin):
    # 条件を満たさない場合に403画面に移動させるかどうかのフラグです。
    #   ログインしているユーザーでないと見れないページである場合に使用する
    # Falseなら、ログイン画面に移動させます。 
    raise_exception = False
    # extra_context = {
        # 'search_form': FileSearchForm(),
    # 'title': 'LOGIN', 'template_name': template_name}

    def test_func(self):
      # 今ログインしてるユーザーのpkと、そのユーザー情報画面のpkが同じか、又はスーパーユーザーなら許可
        user = self.request.user
        return user.pk == self.kwargs['pk'] or user.is_superuser


class UserDetail(OnlyYouMixin, generic.DetailView):
    model = User
    template_name = 'jsk/user_detail.html'
    extra_context = {
        'search_form': FileSearchForm(),
        'title': 'ユーザー基本情報', 'template_name': template_name}


class UserUpdate(OnlyYouMixin, generic.UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'jsk/user_update_input.html'
    extra_context = {
        'search_form': FileSearchForm(),
        'title': 'アカウント編集', 'template_name': template_name}

    def get_success_url(self):

joseikun_keyless/joseikun/jsk/templates/jsk/base.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1,  "> -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">


    <!-- <link rel="icon" type="image/png" href="{% static '北部.png'%}"> -->
    <link rel="icon" type="image/png" href="{% static 'tag.png'%}">

<!-- cssのリンク -->
    <link rel ="stylesheet"href="{% static 'jsk/css/base.css' %}">
    <link rel ="stylesheet" href="{% static 'jsk/css/popup.css' %}">

    <!-- Bootstrap CSS -->
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
          integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous"> -->
  
    <title>{{title}}｜情整君。</title>
</head>
<body>
  <nav>
    <div>
        <ul>
          {% if user.is_authenticated %}
          <!-- サイドバーの記述 -->
          <div title = "トップページへ戻る" class="top">
              <!-- <a href="{% url 'jsk:top' %}">とっぷページへのリンク</a> -->
             <a href="{% url 'jsk:file_search' %}">情整君。</a>
          </div>
            <div class="header">
              <form class = "find" action="{% url 'jsk:file_search' %}" method="get">
                {% comment %} request.GET.検索用語 でデータを送る {% endcomment %}
                {% comment %} <input name="file_name" value="{{ request.GET.file_name }}" type="text"> {% endcomment %}
                {{ search_form.search_name }}
                <button class = "find_box" type="submit">検索する</button>
                {% for method in search_form.search %}
                {{ method }}
                {% endfor %}
                {% comment %} <input type="radio" id="search_radio1" name="search" value="file" checked>
                <label for="search_radio1">ファイル名</label>
                <input type="radio" id="search_radio2" name="search" value="tag">
                <label for="search_radio2">タグ</label> {% endcomment %}
                {% csrf_token %}
              </form>
              <!-- 検索の部分 -->
              <!-- 以下サイドバーの中身 -->
              <input type="checkbox" class="openSidebarMenu" id="openSidebarMenu">
              <label for="openSidebarMenu" class="sidebarIconToggle" id = "sidebarIconToggle">
                <div class="spinner diagonal part-1"></div>
                <div class="spinner horizontal"></div>
                <div class="spinner diagonal part-2"></div>
              </label>
              <div id="sidebarMenu">
                <ul class="sidebarMenuInner">
                  <li><a href="{% url 'jsk:file_upload_image' %}">画像を文書化</a></li>
                  <li><a href="{% url 'jsk:file_upload_text' %}" >文書ファイルを<br>読み込む</a></li>
                  <li><a href="{% url 'jsk:file_search' %}">ファイル検索</a></li>
                  <li><a href="{% url 'jsk:user_detail' user.pk %}">ユーザー情報</a></li>
                  <li><a onclick="log_out_pop()">ログアウト</a></li>
                </ul>
              </div>
            <div id='center' class="main center">
              <div class="mainInner">
          </li>

          {% endif %}
        </ul>
      </div>
    </nav>
    <div">
    {% if not request.user.is_anonymous %}
    {% if not user.is_regist %}
    <p class = "hontouroku">本登録がまだ完了していません。</p>
    {% endif %}
    {% endif %}
    <!-- HTMLファイル名の表示 -->
    <div class = "content" onclick="check()">
      {% block content %}{% endblock %}
      
    </div>
  </div>
<p id = "pop"></p>
  </body>
<script src="{% static 'jsk/js/popup.js' %}"></script>
<script src="{% static 'jsk/js/sidebar.js' %}"></script>
</html>

joseikun_keyless/joseikun/jsk/templates/jsk/file_search.html
{% extends "jsk/base.html" %}
{% load static %}
{% load tag_library %}
{% block content %}
<link rel ="stylesheet"href="{% static 'jsk/css/file_search.css' %}">
<h3>
{% if search.is %}
「{{ search.name }}」で{{ search.method }}：{{ count_result }}
{% else %}
<br>
ファイル一覧を表示
{% endif %}
</h3>
{% comment %} 
<form action="" method="get">
    request.GET.検索用語 でデータを送る 
    <input name="file_name" value="{{ request.GET.file_name }}" type="text">
    <button type="submit">検索する</button>
</form>
{% endcomment %}
<table border="1" class = "file_table">
<tr>
    <!-- <td>ID</td> -->
    <td>ファイルの名前</td>
    <!-- <td>ファイル名</td>
    <td>拡張子</td>
    <td>S3ファイル名</td>
    <td>タグ</td>
    <td>更新日時</td> -->
    <td>最終更新日時</td>
    <!-- <td>詳細</td> -->
</tr>

{% for file in file_list %}
<tr class = "table_file_django">
    <td class = "fname"><div title="クリックしてダウンロード">
    <!-- {% static 'jsk/img/' as baseUrl %} -->
    {% with 'jsk/img/'|add:file.file_extension|add:'.png' as image_static %}
    <a class = "file_dl" href="{% url 'jsk:file_download' %}?param={{file.pk}}">
        <input class = "file_image" type = "image" src = "{% static image_static %}" >
        <span data-text="{{ file }}をダウンロード">{{ file| truncatechars:20 }}</span></a>
        {% endwith %}
    </div>
    </td>
    <td class="last_file">{{ file.last_viewed_dt }}</td>
    <td class= "drop_button">
        <li class = "nav-item dropdown">
            <a class = "nav-link">
                <span></span>
            </a>
            <nav class = "submenu">
                <ul clss = "submenu-items">
                    <li class = "submenu-item"><a href = "{% url 'jsk:file_download' %}?param={{file.pk}}"  class = "submenu-link">ＤＬ</a></li>
                    {% if file.pic_flag %}
                        <li class = "submenu-item"><a href = "{% url 'jsk:file_download_pic' %}?param={{file.pk}}"  class = "submenu-link">元画像ＤＬ</a></li>
                    {% endif %}
                    <li class="submenu-item"><a href="{% url 'jsk:file_detail' file.user_id file.pk %}" class="submenu-link">詳細</a></li>
                    <li class="submenu-item"><a href="{% url 'jsk:file_update_tags' file.user_id file.pk %}" class="submenu-link">編集</a></li>
                    <li class="submenu-item"><a href="{% url 'jsk:text_to_tags' file.user_id file.pk %}" class="submenu-link">タグの生成</a></li>
                    <!-- <li class="submenu-item" ><button class="submenu-link" onclick='popup("{{ file }}","{% url 'jsk:file_delete'%}")'>削除</button></li> -->
                    <li class="submenu-item" ><button class="submenu-link" onclick='popup("{{ file }}","?param={{ file.pk }}")'>削除</button></li>
                </ul>
            </nav>
        </li>
    </td>
    <td> <butto class = tag_button onclick="tag_display('{{forloop.counter}}')">タグ表示</button></td>
</tr>
<tr class = tag_table>
    <td colspan="4">
            <!-- <form class = "find" action="{% url 'jsk:file_search' %}" method="get"> -->
            {% for tag in file.tag_name %}
            <div title="クリックして検索">
            <li class="tag"><a href="{% url 'jsk:file_search' %}?search_name={{ tag }}&search=tag">{{ tag }}</a></li>
            </div>
            {% endfor %}
            <!-- </form> -->
    </td>
</tr>
<!-- {{forloop.counter}} -->

{% endfor %}
</table>
<!-- <p id = "pop"></p> -->

<nav aria-label="ページネーション">
    <div class="pager">
        <ul class="pagination">

        {% if page_obj.has_previous %}
        <li class="page-item">
        <a class="page-link" href="?search_name={{ search_form.search_name.value }}&search={{ search_form.search.value }}&page={{ page_obj.previous_page_number }}" aria-label="前へ">
        <span aria-hidden="true">&laquo;</span>
        </a>
        </li>
        {% endif %}
        {% for page_num in page_obj.paginator.page_range %} 
        {% if page_num == page_obj.number %}
        <li class="page-item active">
        <a class="page-link" href="?search_name={{ search_form.search_name.value }}&search={{ search_form.search.value }}&page={{ page_num }}"><span>{{ page_num }}</span></a>
        </li>
        {% else %}
        <li class="page-item">
        <a class="page-link" href="?search_name={{ search_form.search_name.value }}&search={{ search_form.search.value }}&page={{ page_num }}"><span>{{ page_num }}</span></a>
        </li>
        {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
        <a class="page-link" href="?search_name={{ search_form.search_name.value }}&search={{ search_form.search.value }}&page={{ page_obj.next_page_number }}" aria-label="次へ">
        <span aria-hidden="true">&raquo;</span>
        </a>
        </li>
        {% endif %}

        </ul>
    </div>
</nav>

<script src="{% static 'jsk/js/dropdown.js' %}"></script>
{% endblock %}

joseikun_keyless/joseikun/jsk/templates/jsk/home.html
{% extends "jsk/base.html" %}
{% block content %}
未実装のページ
<p>情整君。のほーむページ</p>
{% endblock %}

joseikun_keyless/joseikun/jsk/templates/jsk/login.html
<title>{{title}}｜情整君。</title>
{% block content %}
{% load static %}

<link rel ="stylesheet" 
        href="{% static 'jsk/css/login.css' %}">

<link rel ="stylesheet" 
        href="{% static 'jsk/css/back_collar.css' %}">

<hr>

<h1 class="kuhaku"></h1>
<h1 class="login">ログイン</h1>


<div>
    <!-- 左側、ログインエリア -->
    <div>
        <div>
            <form class="fo" action="{% url 'jsk:login' %}" method="POST">
                {% csrf_token %}
                {% if form.non_field_errors %}
                    <div>
                    {% for error in form.non_field_errors %}
                        <p{% if forloop.last %} class="mb-0"{% endif %}>正しいメールアドレスとパスワードを入力してください。<br>どちらのフィールドも大文字と小文字は区別されます。</p>
                    {% endfor %}
                    </div>
                {% endif %}
                <table>
                {% for field in form %}
                <tr>
                  <td class="login_text">
                      <label class="lab" for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
                  </td>
                  <td class="login_text2">
                    {{ field }}
                    {{ field.errors }}
                  </td>
                </tr>
                
                {% endfor %}
                <tr><td></td>
                    <td>
                        <button class="but1" type="submit">ログイン</button>
                        <input type="hidden" name="next" value="{{ next }}" />

                    </td>
                </tr>

                <tr><td></td>
                    <td>
                        <div class="card col-md-6">
                            <div class="card-body">
                                <a class="top_link" href="{% url 'jsk:top' %}">トップ画面へ</a>
                            </div>
                    </td>
                </tr>
                        </div>
                        <tr><td></td>
                    <td>
                        <!-- 中央、会員登録エリア -->
                        <div class="card col-md-6">
                            <div class="card-body">
                                <a class="password" href="{% url 'jsk:password_reset' %}">パスワードを忘れた方</a>
                            </div>
                        </div><!-- 中央、会員登録エリアおわり -->
                    </td>
                </tr>
                <tr><td></td>
                    <td>
                        <div class="card col-md-6">
                            <div class="card-body">
                                <a class="acanto" href="{% url 'jsk:user_create_input' %}">アカウント登録が<br>まだの方はコチラへ</a>
                            </div>
                        </div>
                            </td>
                        </tr>
                </table>
            </form>
        </div>
    </div><!-- 左側、ログインエリアおわり -->
    
</div>
{% endblock %}